spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sriteja1
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#employee-details-api endpoint url details
employee-details-api-endpoint-get-url:  http://localhost:2222/api/get-employee-details-based-on-employeeid/
employee-details-api-endpoint-post-url:  http://localhost:2222/api/add-employee-details